# Generated by Django 3.1.5 on 2021-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0002_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelephone',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
