# Generated by Django 3.1.5 on 2021-02-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0003_modelephone_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('couleur', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_modele', models.ForeignKey(db_column='id_modele', on_delete=django.db.models.deletion.DO_NOTHING, to='achat.modelephone')),
            ],
            options={
                'db_table': 'colorphone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PricePhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('capacite', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_color', models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.DO_NOTHING, to='achat.colorphone')),
            ],
            options={
                'db_table': 'pricephone',
                'managed': True,
            },
        ),
    ]
