# Generated by Django 3.0.5 on 2021-02-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0004_colorphone_pricephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='id_phone',
        ),
        migrations.AddField(
            model_name='panier',
            name='id_price_phone',
            field=models.ForeignKey(db_column='id_price_phone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='achat.PricePhone'),
        ),
    ]
