# Generated by Django 3.1.5 on 2021-03-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricephone',
            name='troc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_modele', models.ForeignKey(db_column='id_modele', on_delete=django.db.models.deletion.DO_NOTHING, to='achat.modelephone')),
            ],
            options={
                'db_table': 'panne',
                'managed': True,
            },
        ),
    ]
