# Generated by Django 3.1.5 on 2021-03-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0007_auto_20210306_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricephone',
            name='troc',
        ),
        migrations.AddField(
            model_name='modelephone',
            name='troc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
