# Generated by Django 3.1.5 on 2021-04-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0008_auto_20210306_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite', models.CharField(blank=True, max_length=255, null=True)),
                ('etat', models.CharField(blank=True, max_length=255, null=True)),
                ('allum_bouton', models.CharField(blank=True, max_length=255, null=True)),
                ('boitier', models.CharField(blank=True, max_length=255, null=True)),
                ('ecran_camera', models.CharField(blank=True, max_length=255, null=True)),
                ('imei', models.CharField(blank=True, max_length=255, null=True)),
                ('panier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='achat.panier')),
            ],
        ),
    ]
