# Generated by Django 3.1.5 on 2021-04-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achat', '0009_troc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('panne', models.CharField(blank=True, max_length=255, null=True)),
                ('description_panne', models.TextField(blank=True, null=True)),
                ('date_rdv', models.DateField(blank=True, null=True)),
                ('heure_rdv', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_users', models.ForeignKey(db_column='id_users', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rdv',
                'managed': True,
            },
        ),
    ]
