# Generated by Django 3.1.5 on 2021-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achat', '0011_rdv_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelephone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
