from .commande_model import Commande
from .marque_model import Marque
from .modele_model import ModelePhone
from .panier_model import Panier
from .phone_model import Phone
from .color_phone_model import ColorPhone
from .price_phone_model import PricePhone
from .client_model import Client
from .panne_model import Panne